[package]
name = "lunarfetch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
owo-colors = { version = "3.5.0", features = ["supports-colors"] }
pretty-duration = "0.1.1"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
tokio = { version = "1.32.0", features = ["full"] }
uptime_lib = "0.2.2"
walkdir = "2.4.0"
zbus = { version = "3.14.1", features = ["tokio"] }
zvariant = "3.15.0"
