on:
  push:
    branches:
      - mistress
    tags:
      - "v*.*.*"

name: Release Packaging
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release Packaging
    env:
      PROJECT_NAME: lunarfetch
    runs-on: ubuntu-latest
    container:
      image: rust:alpine
    strategy:
      fail-fast: true
      matrix:
        target: [x86_64-unknown-linux-musl, aarch64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@v4
      - name: install deps
        run: apk update && apk upgrade && apk add musl-dev

      - uses: Swatinem/rust-cache@v2

      - name: Release Build
        run: cargo build --release --target ${{ matrix.target }}

      - uses: actions/upload-artifact@v3
        if: github.ref == 'refs/heads/mistress'
        with:
          name: ${{ env.PROJECT_NAME }}-${{ matrix.target }}
          path: target/release/${{ matrix.target }}/${{ env.PROJECT_NAME }}

      - name: Publish
        id: publishing
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            target/release/${{ matrix.target }}/${{ env.PROJECT_NAME }}
          draft: true
